repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
        -   id: black

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.272
    hooks:
        -   id: ruff
            args: [--fix]

-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
        -   id: flake8

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.6.0
    hooks:
        -   id: pyupgrade
            args: [--py310-plus]

-   repo: local
    hooks:
        -   id: pytest-check
            name: pytest-check
            entry: poetry
            language: system
            always_run: true
            pass_filenames: false
            args: [run, pytest, tests/, -vv]

-   repo: local
    hooks:
        -   id: poetry-check
            name: poetry-check
            entry: poetry
            language: system
            always_run: true
            pass_filenames: false
            args: [check]
