# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.poetry/bin:$PATH"
          poetry --version

      - name: Installer dependencies
        run: poetry install
        
      - name: pre-commit
        # You may pin to the exact commit or the version.
        # uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507
        uses: pre-commit/action@v3.0.0
        with:
          # options to pass to pre-commit run
          args: "--all-files -v"

