# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.poetry/bin:$PATH"
          poetry --version

      - name: Installer dependencies
        run: poetry install
        
      - name: Run linters
        run: |
          poetry run black
          poetry run ruff check.
          poetry run flake8
          poetry run pyupgrade --py310-plus
      
      - name: Run pytest
        run: |
          poetry run pytest tests/ -vv
          
      - name: Check poetry config
        run: |
          poetry check

